#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre commit checks"

# Run lint-staged
npx lint-staged

# Run all tests
echo "Running tests"
npm test -- --watchAll=false --passWithNoTests

echo "All checks passed, committing"